services:
  - type: web
    name: syncra
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        value: 242721714365-b51jtgln62q8eev212c1737ol5d46mpt.apps.googleusercontent.com

